# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Name of the Table')),
                ('document', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Data Table',
            },
        ),
        migrations.CreateModel(
            name='SlotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='OBJECTID')),
                ('shape', models.CharField(blank=True, max_length=250, verbose_name='Shape')),
                ('observer', models.CharField(blank=True, max_length=100, verbose_name='Observer')),
                ('colect_no', models.CharField(blank=True, max_length=50, verbose_name='COLECT_NO')),
                ('colect_no_num', models.CharField(blank=True, max_length=50, verbose_name='COLECT_NO_NUM')),
                ('ob_date', models.CharField(blank=True, max_length=50, verbose_name='OB_Date')),
                ('ob_hh', models.CharField(blank=True, max_length=50, verbose_name='OB_HH')),
                ('ob_mm', models.CharField(blank=True, max_length=50, verbose_name='OB_MM')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='MAJOR')),
                ('loc_munic', models.CharField(blank=True, max_length=250, verbose_name='Loc_Munic')),
                ('minor', models.CharField(blank=True, max_length=100, verbose_name='MINOR')),
                ('park', models.CharField(blank=True, max_length=250, verbose_name='Park')),
                ('centre_ed', models.CharField(blank=True, max_length=250, verbose_name='Centre_ED')),
                ('precise', models.TextField(blank=True, max_length=500, verbose_name='PRECISE')),
                ('site_code', models.CharField(blank=True, max_length=250, verbose_name='Site_code')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='NOTES')),
                ('notes_2', models.TextField(blank=True, max_length=1000, verbose_name='NOTES_2')),
                ('abundance', models.CharField(blank=True, max_length=250, verbose_name='Abundance')),
                ('veg_type', models.CharField(blank=True, max_length=100, verbose_name='VEG_TYPE')),
                ('habitat', models.CharField(blank=True, max_length=250, verbose_name='Habitat')),
                ('substrat', models.CharField(blank=True, max_length=250, verbose_name='SUBSTRAT')),
                ('soile', models.CharField(blank=True, max_length=250, verbose_name='SOILE')),
                ('moisture', models.CharField(blank=True, max_length=250, verbose_name='MOISTURE')),
                ('exposure', models.CharField(blank=True, max_length=250, verbose_name='EXPOSURE')),
                ('lithology', models.CharField(blank=True, max_length=250, verbose_name='LITHOLOGY')),
                ('biotic_efe', models.CharField(blank=True, max_length=250, verbose_name='Biotic_Efe')),
                ('aspect', models.CharField(blank=True, max_length=100, verbose_name='ASPECT')),
                ('asp_no', models.CharField(blank=True, max_length=100, verbose_name='Asp_no')),
                ('asp_mag', models.CharField(blank=True, max_length=100, verbose_name='Asp_mag')),
                ('mag_decline', models.CharField(blank=True, max_length=100, verbose_name='Mag_decline')),
                ('slope', models.CharField(blank=True, max_length=250, verbose_name='SLOPE')),
                ('slope_deg', models.CharField(blank=True, max_length=250, verbose_name='Slope_deg')),
                ('groth_form', models.CharField(blank=True, max_length=250, verbose_name='GROTH_FORM')),
                ('sp_hait', models.CharField(blank=True, max_length=30, verbose_name='SP_HAIT')),
                ('spec_morf', models.CharField(blank=True, max_length=250, verbose_name='SPEC_MORF')),
                ('ob_type', models.CharField(blank=True, max_length=250, verbose_name='OB_type')),
                ('ob_method', models.CharField(blank=True, max_length=250, verbose_name='OB_method')),
                ('spes_tipe', models.CharField(blank=True, max_length=250, verbose_name='SPES_TIPE')),
                ('herb', models.CharField(blank=True, max_length=250, verbose_name='Herb')),
                ('p_name', models.CharField(blank=True, max_length=250, verbose_name='p_name')),
                ('name', models.TextField(blank=True, max_length=500, verbose_name='name')),
                ('sp_no', models.CharField(blank=True, max_length=100, verbose_name='sp_no')),
                ('sp_no_pre', models.CharField(blank=True, max_length=100, verbose_name='sp_no_PRE')),
                ('grid_ref', models.CharField(blank=True, max_length=100, verbose_name='Grid_Ref')),
                ('pentad', models.CharField(blank=True, max_length=100, verbose_name='PENTAD')),
                ('alt', models.CharField(blank=True, max_length=100, verbose_name='alt')),
                ('point_x', models.CharField(blank=True, max_length=10, verbose_name='POINT_X')),
                ('point_y', models.CharField(blank=True, max_length=10, verbose_name='POINT_Y')),
                ('point_z', models.CharField(blank=True, max_length=10, verbose_name='POINT_Z')),
                ('point_m', models.CharField(blank=True, max_length=10, verbose_name='POINT_M')),
                ('x_h', models.CharField(blank=True, max_length=10, verbose_name='x_h')),
                ('x_m', models.CharField(blank=True, max_length=10, verbose_name='x_m')),
                ('x_s', models.CharField(blank=True, max_length=10, verbose_name='x_s')),
                ('y_h', models.CharField(blank=True, max_length=10, verbose_name='y_h')),
                ('y_m', models.CharField(blank=True, max_length=10, verbose_name='y_m')),
                ('y_s', models.CharField(blank=True, max_length=10, verbose_name='y_s')),
                ('c_year', models.CharField(blank=True, max_length=10, verbose_name='c_year')),
                ('c_month', models.CharField(blank=True, max_length=10, verbose_name='c_month')),
                ('c_day', models.CharField(blank=True, max_length=10, verbose_name='c_day')),
                ('project', models.CharField(blank=True, max_length=250, verbose_name='Project')),
                ('id_by', models.CharField(blank=True, max_length=250, verbose_name='ID_By')),
                ('verified', models.CharField(blank=True, max_length=250, verbose_name='Verified')),
                ('on_list', models.CharField(blank=True, max_length=100, verbose_name='on_list')),
                ('rd_status', models.CharField(blank=True, max_length=100, verbose_name='RD_status')),
                ('confidence', models.CharField(blank=True, max_length=100, verbose_name='Confidence')),
                ('latitude', models.CharField(blank=True, max_length=100, verbose_name='LATITUDE')),
                ('longitude', models.CharField(blank=True, max_length=100, verbose_name='LONGITUDE')),
                ('data_admin', models.CharField(blank=True, max_length=100, verbose_name='Data_admin')),
                ('i_her_sout', models.CharField(blank=True, max_length=100, verbose_name='I_HER_SOUT')),
                ('need_id', models.CharField(blank=True, max_length=100, verbose_name='NEED_ID')),
                ('det_date', models.CharField(blank=True, max_length=100, verbose_name='Det_date')),
                ('coll_p_no', models.CharField(blank=True, max_length=100, verbose_name='COLL_P_NO')),
                ('ref', models.CharField(blank=True, max_length=250, verbose_name='Ref')),
                ('link2', models.CharField(blank=True, max_length=250, verbose_name='link2')),
                ('lat_long', models.CharField(blank=True, max_length=250, verbose_name='latlong')),
                ('datum', models.CharField(blank=True, max_length=250, verbose_name='datum')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name': 'Slot Data',
            },
        ),
    ]
